const cardData = [
  {
    id: 1,
    name: "Ongtong Khaosoi x Ari",
    rating: 4.8,
    reviews: 247,
    categories: ["อาหารไทยภาคเหนือ", "ข้าวซอย"],
    img: "/img/h4.jpg",
    location: "อาหารเหนือจากเชียงใหม่",
    tags: ["ข้าวซอย", "น้ำพริกหนุ่ม", "ขนมจีนน้ำเงี้ยว"],
  },
  {
    id: 2,
    name: "ส้มตำเด้อ (ทองหล่อ)",
    rating: 4.6,
    reviews: 189,
    categories: ["อาหารภาคอีสาน"],
    img: "/img/h5.jpg",
    location: "ปากซอยทองหล่อ 17",
    tags: ["ตำปลาดุกฟู", "ตำซั่วสกลนคร", "หมูปิ้งกะทิสด"],
  },
  {
    id: 3,
    name: "Phed Phed Cafe",
    rating: 4.9,
    reviews: 312,
    categories: ["อาหารภาคอีสาน"],
    img: "/img/h6.jpg",
    location: "เซ็นทรัลลาดพร้าว",
    tags: ["ตำปลาร้ากุ้งสด กุ้งลวก", "ตำข้าวโพดไข่เค็ม", "ยำขนมจีนหมูยอปลาทู"],
  },
  {
    id: 4,
    name: "จันทรโภชนา",
    rating: 4.5,
    reviews: 156,
    categories: ["อาหารตะวันออก"],
    img: "/img/h7.jpg",
    location: "จันทบุรี",
    tags: ["ยำมังคุด รสเด็ด", "ปลาต้มระกำใส่กระวาน"],
  },
  {
    id: 5,
    name: "Din Din Thai Cuisine",
    rating: 4.4,
    reviews: 198,
    categories: ["อาหารใต้"],
    img: "/img/h8.jpg",
    location: "ปากเกร็ด นนทบุรี",
    tags: ["ตับกระเทียม", "ใบเหลียงต้มกะทิ"],
  },
  {
    id: 6,
    name: "กรุงเก่า เตี๋ยวเรือ ริมคลองมะขามเรียง",
    rating: 4.7,
    reviews: 203,
    categories: ["อาหารภาคกลาง"],
    img: "/img/h9.jpg",
    location: "พระนครศรีอยุธย",
    tags: ["น่องไก่ทอด กรุงเก่า", "สะโพกไก่ทอด กรุงเก่า ", "ปีกไก่ทอด กรุงเก่า "],
  },
];
export default cardData;